-- modulo_scalability.md §15-17: capacidade, auto scaling e resiliência
CREATE TABLE "scalability_infra_settings" (
    "id" TEXT NOT NULL DEFAULT 'default',
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "updatedById" INTEGER,
    "maxConcurrentUsers" INTEGER NOT NULL DEFAULT 5000,
    "maxApiRps" INTEGER NOT NULL DEFAULT 800,
    "asEnabled" BOOLEAN NOT NULL DEFAULT false,
    "asMinInstances" INTEGER NOT NULL DEFAULT 2,
    "asMaxInstances" INTEGER NOT NULL DEFAULT 6,
    "asTargetCpu" INTEGER NOT NULL DEFAULT 60,
    "asTargetMemory" INTEGER NOT NULL DEFAULT 70,
    "asRequestsPerInstance" INTEGER NOT NULL DEFAULT 400,
    "asScaleUpThreshold" INTEGER NOT NULL DEFAULT 70,
    "asScaleUpMinutes" INTEGER NOT NULL DEFAULT 5,
    "asScaleDownThreshold" INTEGER NOT NULL DEFAULT 30,
    "asScaleDownMinutes" INTEGER NOT NULL DEFAULT 15,
    "asCooldownMinutes" INTEGER NOT NULL DEFAULT 10,
    "asScheduledJson" TEXT,
    "asEmergencyEnabled" BOOLEAN NOT NULL DEFAULT false,
    "asEmergencyMaxInstances" INTEGER NOT NULL DEFAULT 10,
    "rpoMinutes" INTEGER NOT NULL DEFAULT 1440,
    "rtoMinutes" INTEGER NOT NULL DEFAULT 240,
    "apiReplicas" INTEGER NOT NULL DEFAULT 1,
    "dbReplication" BOOLEAN NOT NULL DEFAULT false,
    "failoverEnabled" BOOLEAN NOT NULL DEFAULT false,
    "loadBalancer" BOOLEAN NOT NULL DEFAULT false,
    "cdnEnabled" BOOLEAN NOT NULL DEFAULT false,
    "drPlanDocumented" BOOLEAN NOT NULL DEFAULT false,
    "lastBackupAt" TIMESTAMP(3),
    "lastRecoveryTestAt" TIMESTAMP(3),
    "lastRecoveryTestOk" BOOLEAN,

    CONSTRAINT "scalability_infra_settings_pkey" PRIMARY KEY ("id")
);
