sonar.projectKey=tututazeni-spec_tututazeni-backend
sonar.organization=tututazeni-spec
sonar.projectName=INNOVA Backend
sonar.projectVersion=1.0
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.json
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/dist/**,**/load-tests/**,**/bruno/**,**/prisma/migrations/**,**/.claude/**,**/frontend/**,**/coverage/**,**/worktrees/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.cpd.exclusions=**/*.dto.ts,**/*.entity.ts,**/*.module.ts

# Cobertura de código (gerada pelo Jest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.scanner.sonarcloud.enabled=true
sonar.qualitygate.wait=true
